#!/usr/bin/env bash

readonly __bunyanVersion='0.1.0'

readonly __bunyanName=`basename $0`
readonly __bunyanHost=`hostname`
readonly __bunyanFormatVersion="0"

__bunyanLevel="${BUNYAN_LOGLEVEL:-30}" # info
__bunyanOutput="${BUNYAN_OUTPUT:-/dev/stderr}"

function __bunyan() {
  # arg 1 is LEVEL
  # arg 2 is MSG

  local _now="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  local _level="$1"
  shift 
  local _logMesg="$@"
  printf "{\"name\":\"%s\",\"hostname\":\"%s\",\"pid\":%s,\"level\":%d,\"msg\":\"%s\",\"time\":\"%s\",\"v\":%s}\n" \
    "$__bunyanName" "$__bunyanHost" "$$" "$_level" "$_logMesg" "$_now" "$__bunyanFormatVersion" > "$__bunyanOutput"
}

function __bunyanSetOutput() {
  local _newOutput="$1"
  if [[ -n "$_newOutput" ]]; then
    __bunyanOutput="$_newOutput"
  fi
}

function __bunyanSetLevel() {
  local _newlevel="$1"

  case "$_newlevel" in
    trace)
      __bunyanLevel=10
      ;;
    debug)
      __bunyanLevel=20
      ;;
    info)
      __bunyanLevel=30
      ;;
    warn)
      __bunyanLevel=40
      ;;
    error)
      __bunyanLevel=50
      ;;
    fatal)
      __bunyanLevel=60
      ;;
    *)
      printf "unknown log level '$_newLevel'\n" >&2
      ;;
  esac
}


function trace() { 
  [[ $__bunyanLevel -le 10 ]] &&  __bunyan 10 "$@" 
}

function debug() { 
  [[ $__bunyanLevel -le 20 ]] && __bunyan 20 "$@" 
}

function info()  { 
  [[ $__bunyanLevel -le 30 ]] && __bunyan 30 "$@" 
}

function warn()  { 
  [[ $__bunyanLevel -le 40 ]] && __bunyan 40 "$@" 
}

function error() { 
  [[ $__bunyanLevel -le 50 ]] && __bunyan 50 "$@" 
}

function fatal() { 
  [[ $__bunyanLevel -le 60 ]] && __bunyan 60 "$@" 
}
